name: 'stream'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

clean-targets:
  - 'target'
  - 'dbt_packages'

vars:
  incremental_lookback_days: 3

models:
  stream:
    +materialized: view
    +persist_docs:
      relation: true
      columns: true

    staging:
      +schema: silver
      +tags: ['staging']

    intermediate:
      +materialized: table
      +schema: silver
      +tags: ['intermediate']

    marts:
      +materialized: table
      +schema: gold
      +tags: ['marts']

      core:
        +tags: ['core', 'daily']

      metrics:
        +tags: ['metrics', 'daily']

snapshots:
  stream:
    +target_schema: silver
    +tags: ['snapshots']
